# Generated by Django 4.2.1 on 2023-05-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0002_rename_contact_farmer_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
