# Generated by Django 4.2.1 on 2023-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0003_alter_farmer_mobile_alter_researcher_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(height_field=150, null=True, upload_to='media/', width_field=100)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
