# Generated by Django 4.2.1 on 2023-05-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0004_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
