# Generated by Django 4.2.1 on 2023-05-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0007_crop_amount_crop_quantity_fertilizer_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
