# Generated by Django 4.2.1 on 2023-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0008_subsidy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
