# Generated by Django 4.2.1 on 2023-05-31 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0009_alter_subsidy_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment1', models.CharField(max_length=100, null=True)),
                ('payment2', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri_app.crop')),
                ('fertilizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri_app.fertilizer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri_app.farmer')),
            ],
        ),
    ]
