# Generated by Django 4.2.1 on 2023-05-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0010_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment1',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment2',
        ),
    ]
