# Generated by Django 4.2.1 on 2023-05-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0011_rename_payment1_booking_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='req_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
