# Generated by Django 4.2.1 on 2023-06-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0012_farmer_req_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='quantity',
            new_name='total_quantity',
        ),
        migrations.RenameField(
            model_name='fertilizer',
            old_name='quantity',
            new_name='total_quantity',
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
