# Generated by Django 4.2.1 on 2023-06-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0014_crop_quantity_fertilizer_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
