# Generated by Django 4.2.1 on 2023-06-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0015_alter_crop_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
