# Generated by Django 4.2.1 on 2023-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0016_alter_crop_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
            ],
        ),
    ]
